package com.enkefalostechnologies.calendarpro.constant

object Constants {
    const val BASE_URL="base_url"
    const val GOOGLE_API_KEY="AIzaSyB4vRR2lEG3fQZMjd1dYzaT4_zilnqPo7c"
    const val GOOGLE_CALENDAR_API_URL= "https://www.googleapis.com/calendar/v3/calendars/"

    const val PASSWORD_PATTERN = "^(?=.*[0-9])(?=.*[A-Z])(?=.*[@#$%^&+=!])(?=\\S+$).{4,}$";
    const val EMAIL_PATTERN="^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}\$"

    const val AVTAR_API="https://ui-avatars.com/api/?name="
    const val  SIGNUP_SUCCESS="Account created successfully."
    const val  VERIFY_CONFIRMATION_CODE="Verify account by entering confirmation code."
    const val  LOGIN_SUCCESS="LoggedIn successfully."
    const val  LOGOUT_SUCCESS="SignedOut successfully."
    const val  PASSWORD_RESET_SUCCESS="Password reset successfully."
    const val  PASSWORD_RESET_MISMATCH="New password and re-entered password must be same."
    const val  VERIFICATION_CODE_SENT_TO_REGISTERED_EMAIL="The code has been sent to the entered mail."
    const val  ERROR_FORM_NAME="Enter name"
    const val  ERROR_FORM_EMAIL="Enter valid email"
    const val  ERROR_EMAIL_REQ="Email is required"
    const val  ERROR_PASSWORD_REQ="Password is required"
    const val  ERROR_FORM_PASSWORD="Password must contain a minimum 8 characters password, combination of uppercase and lowercase letter and number"
    const val  CODE_SENT_TO="The code has been sent to the entered mail."
    const val  ERROR_CODE_EXPIRED="The entered Code is Expired."
    const val  ERROR_CODE_WRONG="Incorrect Code"

    const val INTENT_KEY_USERNAME="username"
    const val INTENT_PURPOSE_PASSWORD_RESET="passwordReset"
    const val INTENT_FROM_SCREEN="fromScreen"
    const val INTENT_CONFIRMATION_CODE="confirmationCode"
    const val INTENT_EMAIL="email"
    const val INTENT_PASSWORD="password"
    const val INTENT_TASK_ID="task_id"
    const val INTENT_CODE="code"
    const val INTENT_FROM_LIST_GROUP="from_list_group_screen"


    const val TOAST_NO_EMAIL_APP_FOUND="No email app found."
    const val TOAST_TASK_MARKED_AS_DONE_SUCCESSFULLY="Task Mark as done successfully."
    const val TOAST_TASK_MARKED_AS_UN_DONE_SUCCESSFULLY="Task Mark as un-done successfully."
    const val TOAST_LIST_GROUP_DELETED_SUCCESSFULLY="Task list group deleted successfully."
    const val TOAST_LIST_GROUP_RENAMED_SUCCESSFULLY="Task list group renamed successfully."
    const val TOAST_FAILURE="Some thing went wrong, please try again after some time."
    const val TOAST_GRAPH_FAILURE="Failed to create graph, please try after sometime."
    const val TOAST_TASK_UPDATED_SUCCESSFULLY="Task updated successfully."
    const val TOAST_TASK_DELETED_SUCCESSFULLY="Task deleted successfully."
    const val TOAST_TASK_MARKED_AS_DONE="Task marked as done."
    const val TOAST_ENTER_NAME="Enter name."
    const val TOAST_ENTER_EMAIL="Enter email."
    const val TOAST_FAILED_TO_UPDATE_PROFILE="Failed to update profile details, please try after some time.."
    const val TOAST_PROFILE_UPDATED_SUCCESSFULLY="Profile updated successfully."
    const val TOAST_PASSWORD_UPDATED_SUCCESSFULLY="Password updated successfully."
    const val TOAST_TIMEOUT="Time out, failed to get response."
    const val TOAST_SOMETHING_WENT_WRONG="Something went wrong, please try after some time..."
    const val TOAST_INCORRECT_USERNAME_PASSWORD="Incorrect username or password."
    const val TOAST_INVALID_OLD_PASSWORD="Incorrect old password."
    const val TOAST_USER_ALREADY_EXIST="User already exist."
    const val TOAST_INCORRECT_CODE="Code entered is incorrect."
    const val TOAST_PASSWORD_RESET_REQUIRED="Password reset is required..."
    const val TOAST_USER_NOT_REGISTERED="user not registered/verified..."
    const val TOAST_LIMIT_EXCEEDED="Attempt limit exceeded, please try after some time."
    const val TOAST_EMAIL_NOT_REGISTERED="Email not registered..."
    const val TOAST_CANCELLED_SIGN_IN_ATTEMPT="Cancelled the sign-in attempt."
    const val TOAST_USER_CONFIRMATION_CODE="Enter valid user confirmation code"
    const val TOAST_USER_CODE="Enter valid code"
    const val ERROR_CODE_REQ="Code is required"

    const val TERMS_AND_CONDITION_URL="https://calendarpro.app/terms-and-conditions.html"
    const val PRIVACY_POLICY_URL="https://calendarpro.app/privacy-policy.html"


    const val FIREBASE_EVENT_APP_INSTALLS="app_installs"
    const val FIREBASE_EVENT_PHONE_ACCEPT="Phone_state"
    const val FIREBASE_EVENT_OVERLAY_ACCEPT="Overlay_accept"
    const val FIREBASE_EVENT_NOTIFICATION_ACCEPT="Notification_accept"
}