package com.dream.friend.common

object Constants {
    const val BASE_URL = "http://24.199.110.55:7800"
    //const val BASE_URL = "http://ec2-54-198-223-167.compute-1.amazonaws.com:7800"
    const val NoInternetConnection = "No internet connection"
    const val ExitMsg = "Are you sure you want to exit?"

    //End Points
    const val TwilioSendOtp="users/sendOtpTwilio"
    const val TwilioVerifyOtp="users/verifyOtpTwilio"
    const val LoginUserWithMobile = "/users/create"
    const val LoginUserWithGoogle = "/users/social-login/google"
    const val UpdateUser = "/users/update/"
    private const val GetAll = "/get-all"
    const val UserSexualOrientations = "/orientation$GetAll"
    const val UserYourInterests = "/hobbies$GetAll"
    const val UserLocation = "/users/update-location/"
    const val subscription = "/subscription/subscriptionPlans"
    const val UserProfileImages = "/users/add-image/"
    const val RealtimeImageUpload = "/users/realtime-user-image/"
    const val BlockUser = "/users/blocked/"
    const val GetBlockedUsers = "/users/get-blocked-users"
    const val LikeUser = "/users/liked/"
    const val RejectedUser = "/users/userRejected-from-whoLike-You/"
    const val DislikeUser = "/users/unliked/"
    const val GetAllUsers = "/users/get-geo-near-users/"
    const val GetMatchedUsersURL = "$BASE_URL/users/get-matched-users"
    const val WhomYouLikeURL = "$BASE_URL/users/get-liked-users"
    const val WhoLikeYouURL = "$BASE_URL/users/get-liked-by-users"
    const val GetAllPets = "/pets$GetAll"
    const val getCombineDataForTellUsAboutYou = "/education/get-all-data"
    const val UpdateLifestyle = "/users/update-lifestyle/"
    const val RtcToken = "/rtc/"
    const val logout = "/users/logout"
    const val lastMessage = "/chat/"
    const val markAsRead = "/chat/messageRead/"
    const val deleteUser = "/users/delete"
    const val FCMToken = "/users/fcmToken"
    const val deleteImage = "/users/delete-image/"
    const val SUBSCRIBE = "/subscriber/create-subscription"
    const val MY_PLAN_BENEFITS = "/subscriber/get-subscription-benefits"
    const val ALL_BENEFITS = "/subscriber/get-all-subscription-benefits"
    const val CALL_DECLINE = "/users/call-decline"
    const val SUPER_LIKE="/users/superLiked"
    const val APPLY_BOOST="/users/apply-boost"
    const val CREATE_UPDATE_SUBSCRIBERS = "/subscriber/create-subscription"
    const val INCOGNITO_MODE="/users/incognito-mode"
    const val NOTIFICATION_ENABLE_DISABLE="/users/notification-update"
    const val VERIFY_OR_UPDATE_EMAIL="/users/verifyEmail"
    const val VERIFY_EMAIL_OTP="/users/verifyOtp"

    const val ProfileSetUpSuccessMsg = "Profile has been updated successfully."
    const val SettingsSetUpSuccessMsg = "Settings have been updated successfully."
    const val ARE_YOU_SURE_YOU_WANT_TO_BLOCK = "Are you sure you want to block this user?"

    const val GET_EDUCATIONS="$BASE_URL/education/get-all-education"
    const val GET_SEXUAL_ORIENTATION="$BASE_URL/orientation/get-all"
    const val GET_RELIGION="$BASE_URL/religion/get-all-religion"
    const val GET_INTERESTS="$BASE_URL/hobbies/get-all"
    const val GET_ADVANCE_FILTER_DATA="$BASE_URL/filter/get-all-advance-filter/"
    const val GET_USER_DETAIL="$BASE_URL/users/get-latestUserData/{userId}"
    const val POST_CREATE_ADVANCE_FILTER_DATA="$BASE_URL/filter/advanceFilter-create/"
    const val DELETE_ADVANCE_FILTER_DATA="$BASE_URL/filter/clear-advance-filter/"



    //links
    const val  URL_privacy_policy= "$BASE_URL/content/privacy-policy"
    const val  URL_help_support= "$BASE_URL/content/help-and-support"
    const val  URL_about_us= "$BASE_URL/content/aboutUs"
    const val  URL_terms_of_service= "$BASE_URL/content/terms-of-service"

}