package com.dream.friend.enums

enum class NotificationType(var value:Int) {
    WHO_LIKE_YOU_NOTIFICATION(1),
    MATCH_NOTIFICATION(2),
    FIRST_TIME_LIKE_NOTIFICATION(3),
    FIRST_TIME_SUPER_LIKE_NOTIFICATION(4),
    REAL_TIME_IMAGE_VERIFIED_NOTIFICATION(5),
    REAL_TIME_IMAGE_PROCESSING_NOTIFICATION(6),
    REAL_TIME_IMAGE_REJECTED_NOTIFICATION(7),

}